### 장바구니 생성
POST http://localhost:8080/carts
Content-Type: application/json
Accept: application/json

{
  "user_id": 1,
  "book_id": 1,
  "quantity": 10
}

### 장바구니 특정 아이템 수량 변경
POST http://localhost:8080/carts/1
Content-Type: application/json
Accept: application/json

{
  "quantity": 5
}


### 장바구니 목록 조회
GET http://localhost:8080/carts/user/1
Accept: application/json


### 장바구니 아이템 삭제
GET http://localhost:8080/carts/1
Accept: application/json
