eureka:
  client:
    enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: true
  cloud:
    bus:
      enabled: false
management:
  health:
    rabbit:
      enabled: false
logging:
  level:
    org.hibernate.SQL: debug

minio:
  host: ${MINIO_HOST}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  review-bucket: ink3-dev-reviews-images
  book-bucket: ink3-dev-books-images
  logo-bucket: ink3-logo
payment:
  toss:
    client_key: ${TOSS_PAYMENT_CLIENT_KEY}
    secret_key: ${TOSS_PAYMENT_SECRET_KEY}
elasticsearch:
  url: http://s4.java21.net:9200
  index: ink3_books_dev
  key: ${ELASTIC_KEY}
