spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true



payment:
  toss:
    client_key : "temp"
    secret_key : "temp"
    confirm_url : "https://api.tosspayments.com/v1/payments/confirm"
    success_url : "http://localhost:8084/payment/success"
    fail_url : "http://localhost:8084/payment/fail"
server:
  port: 8084
