spring:
  application:
    name: shop-service

payment:
  toss:
    client_key : ${payment_client_key}
    secret_key : ${payment_secret_key}
    confirm_url : "https://api.tosspayments.com/v1/payments/confirm"
    success_url : "http://localhost:8080/payment/success"
    fail_url : "/payment/fail"
