spring:
  application:
    name: shop-service
  config:
    import: optional:configserver:https://ink3.shop/config/
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    dynamic: false
  cloud:
    bus:
      enabled: true
  minio:
    host: ${MINIO_HOST}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    review-bucket: ink3-dev-reviews-images
    book-bucket: ink3-dev-books-images

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
